# build stage
FROM golang:1.21 AS builder
WORKDIR /app

COPY . .

WORKDIR /app/cmd/worker

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o worker .

# runtime stage
FROM alpine:latest
WORKDIR /root/

COPY --from=builder /app/cmd/worker/worker .

EXPOSE 8080

CMD ["./worker"]
